
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: "matwiecz/io-lab-docker-ci-public:latest"
    build: .
    ports:
      - "80:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    volumes:
      - "redis-data:/data"

volumes:
  redis-data:
